import { AlertCircle, ArrowDownRight, ArrowUpRight, Check, LoaderCircle, Plus, X } from 'lucide-react'
import { money } from '../../utils/format'

export function Button({ children, variant = 'primary', icon: Icon, loading, ...props }) { return <button className={`button button-${variant}`} disabled={loading || props.disabled} {...props}>{loading ? <LoaderCircle className="spin" size={16} /> : Icon ? <Icon size={16} /> : null}{children}</button> }
export function IconButton({ icon: Icon, label, ...props }) { return <button className="icon-button" aria-label={label} {...props}><Icon size={18} /></button> }
export function SectionHeader({ title, action, actionLabel = 'View all' }) { return <div className="section-header"><h2>{title}</h2>{action && <button className="text-button" onClick={action}>{actionLabel}<ArrowUpRight size={14} /></button>}</div> }
export function StatCard({ label, value, meta, trend, icon: Icon, tone = 'dark', formatValue = true }) { return <div className={`stat-card ${tone}`}><div className="stat-top"><span className="stat-label">{label}</span>{Icon && <span className="stat-icon"><Icon size={18} /></span>}</div><strong className="stat-value">{formatValue && typeof value === 'number' ? money(value) : value}</strong>{meta && <div className={`stat-meta ${trend === 'down' ? 'negative' : ''}`}>{trend === 'up' ? <ArrowUpRight size={14} /> : trend === 'down' ? <ArrowDownRight size={14} /> : null}{meta}</div>}</div> }
export function EmptyState({ icon: Icon = Check, title, message, action }) { return <div className="empty-state"><span className="empty-icon"><Icon size={22} /></span><h3>{title}</h3><p>{message}</p>{action}</div> }
export function ErrorState({ message, onRetry }) { return <div className="error-state"><AlertCircle size={20} /><span>{message}</span>{onRetry && <button className="text-button" onClick={onRetry}>Retry</button>}</div> }
export function Modal({ title, subtitle, onClose, children }) { return <div className="modal-layer" role="dialog" aria-modal="true"><div className="modal-card"><div className="modal-head"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18} /></button></div>{children}</div></div> }
export function ConfirmModal({ title, message, onClose, onConfirm, loading }) { return <Modal title={title} subtitle={message} onClose={onClose}><div className="modal-actions"><Button variant="ghost" type="button" onClick={onClose}>Cancel</Button><Button type="button" loading={loading} onClick={onConfirm} style={{ background: '#a85f4b' }}>Delete</Button></div></Modal> }
export const PlusButton = ({ children = 'Add new', ...props }) => <Button icon={Plus} {...props}>{children}</Button>
